#!/bin/bash
# Generated by EDP Framework
# Step: floorplan  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/floorplan

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/floorplan
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/floorplan/step.tcl