# Generated by ConfigKit
# Config loading order (later overrides earlier):
#   1. /home/zero/EDP_AI_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/config.yaml
#   2. /home/zero/EDP_AI_2026/resources/flow/initialize/SAMSUNG/S4/dongting/cmds/pnr_innovus/config.yaml
#
# [override] = this file changed a value from an earlier file, [new] = new variable.
#
# Input files: 2

# --- framework variables ---
set edp(step) {place}
set edp(script) {/home/zero/EDP_AI_2026/web/cmds/pnr_innovus/place/step.tcl}
set edp(workdir) {/home/zero/EDP_AI_2026/web/runs/pnr_innovus/place}
set edp(tool) {pnr_innovus}
set edp(foundry) {SAMSUNG}
set edp(node) {S4}
set edp(project) {dongting}
set edp(sub_steps) {global_place detail_place opt_design}

# --- source from: /home/zero/EDP_AI_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/config.yaml ---
set pnr_innovus(lsf,lsf_mode) {1}
set pnr_innovus(lsf,cpu_num) {8}
set pnr_innovus(lsf,queue) {normal}
set pnr_innovus(init,lsf,cpu_num) {16}
set pnr_innovus(place,lsf,cpu_num) {32}
set pnr_innovus(place,lsf,queue) {high}

# --- source from: /home/zero/EDP_AI_2026/resources/flow/initialize/SAMSUNG/S4/dongting/cmds/pnr_innovus/config.yaml ---

