#!/bin/bash
# Generated by EDP Framework
# Step: dummy  Tool: pv_calibre
# Run directory: /home/zero/EDP_AI_2026/web/runs/pv_calibre/dummy

cd /home/zero/EDP_AI_2026/web/runs/pv_calibre/dummy
calibre -dummy |& tee dummy.log