#!/bin/bash
# Generated by EDP Framework
# Step: drc  Tool: pv_calibre
# Run directory: /home/zero/EDP_AI_2026/web/runs/pv_calibre/drc

cd /home/zero/EDP_AI_2026/web/runs/pv_calibre/drc
calibre -drc -hier -turbo 8 |& tee drc.log