#!/bin/csh
# Generated by EDP Framework
# Step: place  Tool: pnr_innovus
# Working directory: C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main

cd C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main
innovus -init C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/cmds/pnr_innovus/place.tcl