# Generated by ConfigKit
# Config loading order (later overrides earlier):
#   1. C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pnr_innovus\config.yaml
#   2. C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pnr_innovus\config.yaml
#   3. C:\Users\anping.chen\Desktop\rewrite_edp_continue\try_new_edp\dongting\P85\pcie\anping.chen\2026_4_21_main\user_config.yaml
#
# Variables prefixed with [overridden] were overridden by a later file.
#
# Input files: 3

# --- framework variables ---
set edp(step) {place}
set edp(script) {C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/cmds/pnr_innovus/place.tcl}
set edp(workdir) {C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/runs/pnr_innovus/place}
set edp(tool) {pnr_innovus}
set edp(foundry) {SAMSUNG}
set edp(node) {S4}
set edp(project) {dongting}
set edp(sub_steps) {global_place detail_place opt_design}

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pnr_innovus\config.yaml ---
set pnr_innovus(lsf,lsf_mode) {1}
set pnr_innovus(lsf,cpu_num) {8}
set pnr_innovus(lsf,queue) {normal}
set pnr_innovus(init,lsf,cpu_num) {16}
set pnr_innovus(place,lsf,cpu_num) {32}
set pnr_innovus(place,lsf,queue) {high}

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pnr_innovus\config.yaml ---

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\try_new_edp\dongting\P85\pcie\anping.chen\2026_4_21_main\user_config.yaml ---
set pv_calibre(test) {1}

