# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: place  Tool: pnr_innovus
# Sub-steps: global_place -> detail_place -> opt_design
# Generated at: 2026-04-23 15:50:38
# Flow base: C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/common_packages/tcl_packages/default/edp_debug.tcl

# --- pnr_innovus/steps/place ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See place_config.tcl for details and variable tracing
# ============================================================

source C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/cmds/pnr_innovus/place_config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl

if {[info procs place_global_place_pre] ne ""} { place_global_place_pre }
global_place

if {[info procs place_global_place_post] ne ""} { place_global_place_post }

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl

if {[info procs place_detail_place_pre] ne ""} { place_detail_place_pre }
detail_place

if {[info procs place_detail_place_post] ne ""} { place_detail_place_post }

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl

if {[info procs place_opt_design_pre] ne ""} { place_opt_design_pre }
opt_design

if {[info procs place_opt_design_post] ne ""} { place_opt_design_post }
