# Generated by ConfigKit
# Config loading order (later overrides earlier):
#   1. C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pnr_innovus\config.yaml
#   2. C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pnr_innovus\config.yaml
#
# [override] = this file changed a value from an earlier file, [new] = new variable.
#
# Input files: 2

# --- framework variables ---
set edp(step) {cts}
set edp(script) {C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/cts/step.tcl}
set edp(workdir) {C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/cts}
set edp(tool) {pnr_innovus}
set edp(foundry) {SAMSUNG}
set edp(node) {S4}
set edp(project) {dongting}
set edp(sub_steps) {}

# --- source from: C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pnr_innovus\config.yaml ---
set pnr_innovus(lsf,lsf_mode) {1}
set pnr_innovus(lsf,cpu_num) {8}
set pnr_innovus(lsf,queue) {normal}
set pnr_innovus(init,lsf,cpu_num) {16}
set pnr_innovus(place,lsf,cpu_num) {32}
set pnr_innovus(place,lsf,queue) {high}

# --- source from: C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pnr_innovus\config.yaml ---

