#!/bin/bash
# Generated by EDP Framework
# Step: init  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/init

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/init
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/init/step.tcl