# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: place  Tool: pnr_innovus
# Sub-steps: global_place -> detail_place -> opt_design
# Generated at: 2026-04-23 18:17:23
# Flow base: C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/common_packages/tcl_packages/default/edp_debug.tcl

# --- pnr_innovus/steps/place ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl

# --- hooks/pnr_innovus/place (proc definitions) ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/detail_place.post
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/detail_place.pre
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/detail_place.replace
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/global_place.post
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/global_place.pre
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/global_place.replace
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/opt_design.post
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/opt_design.pre
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/opt_design.replace
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/step.post
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/hooks/pnr_innovus/place/step.pre


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See place_config.tcl for details and variable tracing
# ============================================================

source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/cmds/pnr_innovus/place_config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================

# --- step.pre: place_step_pre ---
if {[info procs place_step_pre] ne ""} { place_step_pre }

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl

if {[info procs place_global_place_pre] ne ""} { place_global_place_pre }
global_place

if {[info procs place_global_place_post] ne ""} { place_global_place_post }

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl

if {[info procs place_detail_place_pre] ne ""} { place_detail_place_pre }
detail_place

if {[info procs place_detail_place_post] ne ""} { place_detail_place_post }

# C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl

if {[info procs place_opt_design_pre] ne ""} { place_opt_design_pre }
opt_design

if {[info procs place_opt_design_post] ne ""} { place_opt_design_post }

# --- step.post: place_step_post ---
if {[info procs place_step_post] ne ""} { place_step_post }
