#!/bin/bash
# Generated by EDP Framework
# Step: ipmerge  Tool: pv_calibre
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/ipmerge

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/ipmerge
calibre -ipmerge |& tee ipmerge.log