#!/bin/bash
# Generated by EDP Framework
# Step: place  Tool: pnr_innovus
# Run directory: C:/Users/Administrator/Desktop/edp_ai/EDP_AI_2026/try_new_edp/dongting/P85/pcie/Administrator/2026_4_23_main/runs/pnr_innovus/place

cd C:/Users/Administrator/Desktop/edp_ai/EDP_AI_2026/try_new_edp/dongting/P85/pcie/Administrator/2026_4_23_main/runs/pnr_innovus/place
innovus -init C:/Users/Administrator/Desktop/edp_ai/EDP_AI_2026/try_new_edp/dongting/P85/pcie/Administrator/2026_4_23_main/cmds/pnr_innovus/place.tcl