#!/bin/bash
# Generated by EDP Framework
# Step: place  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/place

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/place
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/place/step.tcl