# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: dummy  Tool: pv_calibre
# Sub-steps: 
# Generated at: 2026-04-26 22:54:45
# Flow base: /home/zero/EDP_AI_2026/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source /home/zero/EDP_AI_2026/resources/flow/common_packages/tcl_packages/default/edp_debug.tcl


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See config.tcl for details and variable tracing
# ============================================================

source /home/zero/EDP_AI_2026/web/cmds/pv_calibre/dummy/config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================
