#!/bin/bash
# Generated by EDP Framework
# Step: drc  Tool: pv_calibre
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_28_main/runs/pv_calibre/drc

cd C:/Users/anping.chen/Desktop/EDP_2026/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_28_main/runs/pv_calibre/drc
calibre -drc -hier -turbo 8 |& tee drc.log