#!/bin/bash
# Generated by EDP Framework
# Step: cts  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/cts

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/cts
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/cts/step.tcl