#!/bin/bash
# Generated by EDP Framework
# Step: perc  Tool: pv_calibre
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/perc

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/perc
pv_calibre -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pv_calibre/perc/step.tcl