# Generated by ConfigKit
# Config loading order (later overrides earlier):
#   1. C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pv_calibre\config.yaml
#   2. C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pv_calibre\config.yaml
#
# [override] = this file changed a value from an earlier file, [new] = new variable.
#
# Input files: 2

# --- framework variables ---
set edp(step) {dummy}
set edp(script) {C:/Users/anping.chen/Desktop/EDP_2026/cmds/pv_calibre/dummy/step.tcl}
set edp(workdir) {C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/dummy}
set edp(tool) {pv_calibre}
set edp(foundry) {SAMSUNG}
set edp(node) {S4}
set edp(project) {dongting}
set edp(sub_steps) {}

# --- source from: C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pv_calibre\config.yaml ---
set pv_calibre(lsf,lsf_mode) {1}
set pv_calibre(lsf,cpu_num) {4}
set pv_calibre(lsf,queue) {normal}
set pv_calibre(tee) {|& tee}
set pv_calibre(drc,svrf_dir) {.}
set pv_calibre(drc,svrf_name) {drc.svrf}
set pv_calibre(drc,cpu_num) {8}
set pv_calibre(drc,lsf,cpu_num) {16}
set pv_calibre(drc,lsf,queue) {verify}
set pv_calibre(lvs,cpu_num) {8}
set pv_calibre(lvs,lsf,cpu_num) {4}
set pv_calibre(lvs,lsf,queue) {verify}
set pv_calibre(perc,cpu_num) {8}
set pv_calibre(perc,lsf,cpu_num) {4}
set pv_calibre(perc,lsf,queue) {verify}
set pv_calibre(ipmerge,cpu_num) {4}
set pv_calibre(dummy,cpu_num) {4}

# --- source from: C:\Users\anping.chen\Desktop\EDP_2026\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pv_calibre\config.yaml ---

