#!/bin/bash
# Generated by EDP Framework
# Step: floorplan  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/floorplan

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/floorplan
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/floorplan/step.tcl