#!/bin/bash
# Generated by EDP Framework
# Step: place  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/place

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/place
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/place/step.tcl