proc prepare_svrf {} {
    # Build path from pure YAML data keys: svrf_dir + svrf_name.
    # Then generate a runnable shell wrapper for the real calibre command.
    global edp
    global pv_calibre

    set svrf_dir "."
    set svrf_name "drc.svrf"
    set cpu_num 4
    set tee_pipe "|& tee $edp(step).log"

    if {[info exists pv_calibre(drc,svrf_dir)] && $pv_calibre(drc,svrf_dir) ne ""} {
        set svrf_dir $pv_calibre(drc,svrf_dir)
    }
    if {[info exists pv_calibre(drc,svrf_name)] && $pv_calibre(drc,svrf_name) ne ""} {
        set svrf_name $pv_calibre(drc,svrf_name)
    }
    if {[info exists pv_calibre(drc,cpu_num)] && $pv_calibre(drc,cpu_num) ne ""} {
        set cpu_num $pv_calibre(drc,cpu_num)
    } elseif {[info exists pv_calibre(cpu_num)] && $pv_calibre(cpu_num) ne ""} {
        set cpu_num $pv_calibre(cpu_num)
    }
    if {[info exists pv_calibre(tee)] && $pv_calibre(tee) ne ""} {
        set tee_pipe "$pv_calibre(tee) $edp(step).log"
    }

    set svrf_path [file normalize [file join $svrf_dir $svrf_name]]
    file mkdir [file dirname $svrf_path]

    set fp [open $svrf_path "w"]
    puts $fp "# Auto-generated by EDP: $::edp(step)"
    puts $fp "# TODO: populate real Calibre DRC deck content."
    close $fp
    puts "Generated $svrf_path"

    set run_script [file normalize "run_drc.sh"]
    set rf [open $run_script "w"]
    puts $rf "#!/bin/bash"
    puts $rf "set -euo pipefail"
    puts $rf "calibre -drc -hier -turbo $cpu_num $svrf_path $tee_pipe"
    close $rf
    file attributes $run_script -permissions u+rwx
    puts "Generated $run_script"
}

