# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: drc  Tool: pv_calibre
# Sub-steps: 
# Generated at: 2026-04-23 15:48:42
# Flow base: C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source C:/Users/anping.chen/Desktop/rewrite_edp_continue/new_edp/resources/common_packages/tcl_packages/default/edp_debug.tcl


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See drc_config.tcl for details and variable tracing
# ============================================================

source C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/cmds/pv_calibre/drc_config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================
