# Generated by ConfigKit
# Config loading order (later overrides earlier):
#   1. C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pv_calibre\config.yaml
#   2. C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pv_calibre\config.yaml
#   3. C:\Users\anping.chen\Desktop\rewrite_edp_continue\try_new_edp\dongting\P85\pcie\anping.chen\2026_4_21_main\user_config.yaml
#
# Variables prefixed with [overridden] were overridden by a later file.
#
# Input files: 3

# --- framework variables ---
set edp(step) {drc}
set edp(script) {C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/cmds/pv_calibre/drc.tcl}
set edp(workdir) {C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_21_main/runs/pv_calibre/drc}
set edp(tool) {pv_calibre}
set edp(foundry) {SAMSUNG}
set edp(node) {S4}
set edp(project) {dongting}
set edp(sub_steps) {}

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\common_prj\cmds\pv_calibre\config.yaml ---
set pv_calibre(lsf,lsf_mode) {1}
set pv_calibre(lsf,cpu_num) {4}
set pv_calibre(lsf,queue) {normal}
set pv_calibre(drc,lsf,cpu_num) {16}
set pv_calibre(drc,lsf,queue) {verify}

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\new_edp\resources\flow\initialize\SAMSUNG\S4\dongting\cmds\pv_calibre\config.yaml ---

# --- source from: C:\Users\anping.chen\Desktop\rewrite_edp_continue\try_new_edp\dongting\P85\pcie\anping.chen\2026_4_21_main\user_config.yaml ---
set pv_calibre(test) {1}

