#!/bin/bash
# Generated by EDP Framework
# Step: postroute  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/postroute

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/postroute
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/postroute/step.tcl