#!/bin/bash
# Generated by EDP Framework
# Step: route  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/route

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/route
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/route/step.tcl