#!/bin/bash
# Generated by EDP Framework
# Step: postroute  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/postroute

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/postroute
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/postroute/step.tcl