#!/bin/bash
# Generated by EDP Framework
# Step: dummy  Tool: pv_calibre
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/dummy

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/dummy
calibre -dummy |& tee dummy.log