#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
ConfigKit Tcl 文件输出模块。

负责将 YAML/Tcl 配置链合成为单个 Tcl 文件，供 TclBridge 委托调用。
"""

import re
from pathlib import Path
from tkinter import Tcl
from typing import Any, Dict, List, Optional, Tuple, Union

import yaml


def _flatten_dict(data: Dict[str, Any],
                  parent_keys: Optional[List[str]] = None) -> List[Tuple[str, str]]:
    """将嵌套字典扁平化为 (tcl_key, value) 列表。"""
    parent_keys = parent_keys or []
    result: List[Tuple[str, str]] = []

    for key, value in data.items():
        if isinstance(value, dict):
            result.extend(_flatten_dict(value, parent_keys + [key]))
        elif isinstance(value, list):
            tcl_elements = " ".join(str(v) for v in value)
            if parent_keys:
                tcl_key = f"{parent_keys[0]}({','.join(parent_keys[1:] + [key])})"
            else:
                tcl_key = key
            result.append((tcl_key, f"[list {tcl_elements}]"))
        else:
            if parent_keys:
                tcl_key = f"{parent_keys[0]}({','.join(parent_keys[1:] + [key])})"
            else:
                tcl_key = key
            result.append((tcl_key, str(value) if value is not None else ""))

    return result


def files_to_tcl(interp: Tcl,
                 *input_files: Union[str, Path],
                 output_file: Union[str, Path],
                 edp_vars: Optional[Dict[str, str]] = None) -> Path:
    """将多个 YAML/Tcl 配置文件按覆盖链合成为单个 Tcl 文件。"""
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if edp_vars:
        for key, value in edp_vars.items():
            interp.eval(f"set edp({key}) {{{value}}}")

    def _get_interp_var(var_name: str) -> str:
        try:
            return interp.eval(f"set {var_name}")
        except Exception:
            return ""

    def _expand_refs(value: str) -> str:
        def _replacer_array(match_obj):
            var_name = match_obj.group(1)
            val = _get_interp_var(var_name)
            return val if val else match_obj.group(0)

        def _replacer_simple(match_obj):
            var_name = match_obj.group(1)
            val = _get_interp_var(var_name)
            return val if val else match_obj.group(0)

        expanded = re.sub(r"\$(\w+\([^)]+\))", _replacer_array, value)
        expanded = re.sub(r"\$(\w+)", _replacer_simple, expanded)
        return expanded

    def _var_exists(tcl_key: str) -> bool:
        try:
            return interp.eval(f"info exists {tcl_key}") == "1"
        except Exception:
            return False

    def _get_var(tcl_key: str) -> str:
        try:
            return interp.eval(f"set {tcl_key}")
        except Exception:
            return ""

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("# Generated by ConfigKit\n")
        out.write(f"# Input files: {len(input_files)}\n")

        if edp_vars:
            out.write("\n# --- framework variables ---\n")
            for key, value in edp_vars.items():
                out.write(f"set edp({key}) {{{value}}}\n")

        out.write("\n")

        for file_idx, input_file in enumerate(input_files):
            file_path = Path(input_file)
            if not file_path.exists():
                continue

            out.write(f"# --- source from: {file_path.resolve()} ---\n")
            ext = file_path.suffix.lower()

            if ext in (".yaml", ".yml"):
                with open(file_path, "r", encoding="utf-8") as f:
                    data = yaml.safe_load(f) or {}
                entries = _flatten_dict(data)
                for tcl_key, value in entries:
                    expanded = _expand_refs(value)

                    mark = ""
                    if file_idx > 0:
                        if _var_exists(tcl_key):
                            old_val = _get_var(tcl_key)
                            if old_val != expanded:
                                mark = f"   # [override] was {{{old_val}}}"
                        else:
                            mark = "   # [new]"

                    out.write(f"set {tcl_key} {{{expanded}}}{mark}\n")
                    interp.eval(f"set {tcl_key} {{{expanded}}}")
                out.write("\n")
            elif ext in (".tcl", ".tk"):
                content = file_path.read_text(encoding="utf-8")
                interp.eval(f"source {{{file_path.resolve()}}}")
                out.write(content)
                if not content.endswith("\n"):
                    out.write("\n")
                out.write("\n")

    return output_path
