#!/bin/bash
# Generated by EDP Framework
# Step: ipmerge  Tool: pv_calibre
# Run directory: /home/zero/EDP_AI_2026/web/runs/pv_calibre/ipmerge

cd /home/zero/EDP_AI_2026/web/runs/pv_calibre/ipmerge
calibre -ipmerge |& tee ipmerge.log