#!/usr/bin/env python
# -*- coding: utf-8 -*-

import shlex
from typing import Optional

from ._script_utils import _posix


def resolve_invoke(builder, tool_name: str, step_name: str,
                   debug: bool = False) -> str:
    """解析 invoke 列表，拼接成完整命令。"""
    invoke_list = builder.registry.get_invoke(tool_name, step_name)
    if not invoke_list:
        return ""

    edp_vars = builder._build_edp_vars(tool_name, step_name, debug=debug)
    config = builder._load_config_dict(tool_name)
    tool_config = config.get(tool_name, {})

    def _resolve_var(var_name: str) -> str:
        if var_name in edp_vars:
            return edp_vars[var_name]
        step_cfg = tool_config.get(step_name, {})
        if isinstance(step_cfg, dict) and var_name in step_cfg:
            return str(step_cfg[var_name])
        if var_name in tool_config:
            return str(tool_config[var_name])
        return ""

    resolved_items = []
    for item in invoke_list:
        cond_vars = builder._COND_PATTERN.findall(item)
        if cond_vars:
            all_resolved = True
            resolved = item
            for var_name in cond_vars:
                value = _resolve_var(var_name)
                if not value:
                    all_resolved = False
                    break
                resolved = resolved.replace(f"{{{var_name}}}", value)
            if not all_resolved:
                continue
            item = resolved

        for var_name in builder._EDP_PATTERN.findall(item):
            value = edp_vars.get(var_name, "")
            item = item.replace(f"$edp({var_name})", value)

        for var_name in builder._VAR_PATTERN.findall(item):
            value = _resolve_var(var_name)
            item = item.replace(f"${var_name}", value)

        validate_safe_invoke_item(builder, item, tool_name, step_name)
        resolved_items.append(item)

    return " ".join(resolved_items)


def validate_safe_invoke_item(builder, item: str, tool_name: str, step_name: str) -> None:
    """阻断高风险 shell 注入片段。"""
    for pattern in builder._UNSAFE_SHELL_PATTERNS:
        if pattern in item:
            raise ValueError(
                f"Unsafe shell pattern '{pattern}' found in invoke item "
                f"for {tool_name}.{step_name}: {item}"
            )


def build_step_shell(builder, tool_name: str, step_name: str,
                     debug: bool = False,
                     shell_type: Optional[str] = None) -> str:
    """生成 .sh/.csh 启动脚本。"""
    command = resolve_invoke(builder, tool_name, step_name, debug=debug)
    if not command:
        return ""

    run_dir = builder.workdir_path / "runs" / tool_name / step_name
    actual_shell = builder._detect_shell(shell_type) if shell_type else builder.preferred_shell
    shebang = "#!/bin/bash" if actual_shell == "bash" else "#!/bin/csh"
    lines = [
        shebang,
        "# Generated by EDP Framework",
        f"# Step: {step_name}  Tool: {tool_name}",
        f"# Run directory: {_posix(run_dir.resolve())}",
        "",
        f"cd {shlex.quote(_posix(run_dir.resolve()))}",
        command,
    ]
    return "\n".join(lines)
