#!/usr/bin/env python
# -*- coding: utf-8 -*-

from datetime import datetime
from pathlib import Path
from typing import Optional

from configkit import files2tcl

from ._script_utils import _posix


def generate_config_tcl(builder, tool_name: str, step_name: str) -> Path:
    """用 configkit.files2tcl 生成 per-step 的 config.tcl。"""
    config_files = []

    def _find_config(directory: Path, filename_stem: str) -> Optional[Path]:
        yaml_path = directory / f"{filename_stem}.yaml"
        if yaml_path.exists():
            return yaml_path
        tcl_path = directory / f"{filename_stem}.tcl"
        if tcl_path.exists():
            return tcl_path
        return None

    cfg = _find_config(builder.flow_base_path / "cmds" / tool_name, "config")
    if cfg:
        config_files.append(cfg)

    if builder.overlay_path:
        cfg = _find_config(builder.overlay_path / "cmds" / tool_name, "config")
        if cfg:
            config_files.append(cfg)

    cfg = _find_config(builder.workdir_path, "user_config")
    if cfg:
        config_files.append(cfg)

    output_path = builder.workdir_path / "cmds" / tool_name / step_name / "config.tcl"
    if not config_files:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            "# Generated by ConfigKit\n# No config files found.\n",
            encoding="utf-8",
        )
        return output_path

    edp_vars = builder._build_edp_vars(tool_name, step_name)
    result = files2tcl(*config_files, output_file=output_path, edp_vars=edp_vars)

    content = result.read_text(encoding="utf-8")
    header_lines = ["# Config loading order (later overrides earlier):"]
    for i, f in enumerate(config_files, 1):
        header_lines.append(f"#   {i}. {f.resolve()}")
    header_lines.append("#")
    header_lines.append("# [override] = this file changed a value from an earlier file, [new] = new variable.")
    header_lines.append("#")

    new_content = content.replace(
        "# Generated by ConfigKit\n",
        "# Generated by ConfigKit\n" + "\n".join(header_lines) + "\n",
        1,
    )
    result.write_text(new_content, encoding="utf-8")
    return result


def build_header(builder, tool_name: str, step_name: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    parts = builder.flow_base_path.parts
    try:
        idx = parts.index("initialize")
        foundry = parts[idx + 1] if idx + 1 < len(parts) else "?"
        node = parts[idx + 2] if idx + 2 < len(parts) else "?"
    except ValueError:
        foundry = "?"
        node = "?"

    project = builder.overlay_path.name if builder.overlay_path else "common"
    lines = [
        "# ============================================================",
        "# Generated by EDP Framework",
        f"# Foundry: {foundry}  Node: {node}  Project: {project}",
        f"# Step: {step_name}  Tool: {tool_name}",
    ]
    if builder.registry.has_step(tool_name, step_name):
        sub_steps = builder.registry.get_sub_steps(tool_name, step_name)
        lines.append(f"# Sub-steps: {' -> '.join(sub_steps)}")
    lines.extend([
        f"# Generated at: {now}",
        f"# Flow base: {_posix(builder.flow_base_path.resolve())}",
        "# ============================================================",
    ])
    return "\n".join(lines)


def build_debug_script(builder, tool_name: str, step_name: str) -> str:
    lines = [
        "# ============================================================",
        "# EDP Debug Mode",
        f"# Step: {step_name}  Tool: {tool_name}",
        "# Source this file in your tool's Tcl shell for interactive debug.",
        "# ============================================================",
        "",
    ]

    source_section = builder._build_source_phase(tool_name, step_name, exclude=["edp_debug.tcl"])
    if source_section:
        lines.append(source_section)

    config_section = builder._build_config_source(tool_name, step_name)
    if config_section:
        lines.append(config_section)

    debug_pkg = builder.common_packages_path / "tcl_packages" / "default" / "edp_debug.tcl"
    if debug_pkg.exists():
        lines.append("# Load debug CLI")
        lines.append(f"source {_posix(debug_pkg.resolve())}")
    else:
        lines.append(f"# WARNING: edp_debug.tcl not found at {_posix(debug_pkg)}")
    return "\n".join(lines)
