#!/bin/csh
# Generated by EDP Framework
# Step: place  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/runs/pnr_innovus/place

cd C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/runs/pnr_innovus/place
innovus -init C:/Users/anping.chen/Desktop/rewrite_edp_continue/try_new_edp/dongting/P85/pcie/anping.chen/2026_4_23_main/cmds/pnr_innovus/place.tcl