#!/bin/bash
# Generated by EDP Framework
# Step: init  Tool: pnr_innovus
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/init

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pnr_innovus/init
innovus -init C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/init/step.tcl