# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: place  Tool: pnr_innovus
# Sub-steps: global_place -> detail_place -> opt_design
# Generated at: 2026-04-28 16:56:12
# Flow base: C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/common_packages/tcl_packages/default/edp_debug.tcl

# --- pnr_innovus/steps/place ---
source C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl
source C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl
source C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See config.tcl for details and variable tracing
# ============================================================

source C:/Users/anping.chen/Desktop/EDP_2026/cmds/pnr_innovus/place/config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================

# C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/global_place.tcl

global_place

# C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/detail_place.tcl

detail_place

# C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj/cmds/pnr_innovus/steps/place/opt_design.tcl

opt_design
