# ============================================================
# Generated by EDP Framework
# Foundry: SAMSUNG  Node: S4  Project: dongting
# Step: ipmerge  Tool: pv_calibre
# Sub-steps: 
# Generated at: 2026-04-28 16:16:02
# Flow base: C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/initialize/SAMSUNG/S4/common_prj
# ============================================================

# ============================================================
# Phase 1: Source
# ============================================================

# --- common_packages/default ---
source C:/Users/anping.chen/Desktop/EDP_2026/resources/flow/common_packages/tcl_packages/default/edp_debug.tcl


# ============================================================
# Config Variables
# Generated from: base -> overlay -> user_config
# See config.tcl for details and variable tracing
# ============================================================

source C:/Users/anping.chen/Desktop/EDP_2026/cmds/pv_calibre/ipmerge/config.tcl


# ============================================================
# Phase 2: Execute
# ============================================================
