#!/bin/bash
# Generated by EDP Framework
# Step: lvs  Tool: pv_calibre
# Run directory: C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/lvs

cd C:/Users/anping.chen/Desktop/EDP_2026/runs/pv_calibre/lvs
calibre -lvs -hier -turbo 8 |& tee lvs.log