#!/bin/bash
# Generated by EDP Framework
# Step: route  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/route

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/route
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/route/step.tcl