#!/bin/bash
# Generated by EDP Framework
# Step: cts  Tool: pnr_innovus
# Run directory: /home/zero/EDP_AI_2026/web/runs/pnr_innovus/cts

cd /home/zero/EDP_AI_2026/web/runs/pnr_innovus/cts
innovus -init /home/zero/EDP_AI_2026/web/cmds/pnr_innovus/cts/step.tcl